### ISSUE TITLE
GUI ACHPMainFrame

### ISSUE THREAD

**Issue by lofuque** [CenterHighPerformanceBuildingsPurdue/ACHP#43]
Hello, I am new to ACHP. But I am very interested in the code. My first test is on interface GUI. I encountered errors while Solve :
Traceback (most recent call last):
  File ".\ACHPMainFrame.py", line 70, in RunCode
    Cycle=GUI2DXCycleInputs(self)
  File "C:\Users\Utilisateur\Travaux\ACHP\ACHP-1\GUI\ACHPFileIO.py", line 57, in GUI2DXCycleInputs
    Cycle.Evaporator.DT_sh              =float(GUI.txtCycleDTsh.GetValue())
AttributeError: DXCycleClass instance has no attribute 'Evaporator'

If you have any comments, it might help me alot. Thanks in advance.

**Comment by abahman** [comment]
cc: @davideziviani
